Bloombloom/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('credentials.urls')),
    path('',include('course_app.urls')),
    path('',include('event_app.urls')),
    path('accounts/', include('allauth.urls')),
    path('',include('category.urls')),

    
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

category/urls.py
from django.urls import  path
from course_app.views import my_view
from category import views

urlpatterns = [
    path('cat_view/',views.cat_view,name='cat_view'),
    path('get_submenu/',views.get_submenu,name='get_submenu'),
    path('get_subsubmenu/', views.get_subsubmenu, name='get_subsubmenu'),
    path('my_view/',my_view,name="my_view"),
    # path('course_interest/',course_interest,name="course_interest"),

]

credentials/urls.py
# urls.py
from django.urls import path
from . import views
from allauth.account.views import SignupView
from .views  import CustomLoginView 
from django.urls import path
from .views import CustomPasswordResetView
from .models import CustomUser
from allauth.socialaccount.providers.oauth2.views import OAuth2CallbackView
from .views import google_oauth_callback


urlpatterns = [
    path('header/',views.header,name='header'),
    path('footer/',views.footer,name='footer'),
    path('accounts/signup/',views.signup_view, name='account_signup'),
    path('accounts/profile/',views.profile, name='profile'),
    path('accounts/login/', CustomLoginView.as_view(), name='login'),
    path('accounts/password/reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('accounts/verify-otp/password_reset/', views.verify_otp, name='verify_otp'),
    path('accounts/reset-password/', views.reset_password, name='reset_password'),
    path('accounts/dob', views.signup_dob, name='dob'),
    path('accounts/signup_password/',views.signup_password,name='signup_password'),
    path('accounts/phone_otp/',views.phone_otp,name='phone_otp'),
    path('accounts/google/callback/', google_oauth_callback, name='google_oauth_callback'),
    path('accounts/google/default_callback/', OAuth2CallbackView, name='default_google_oauth_callback'),
    path('purpose/',views.save_top_purposes_view,name='save_top_purposes_view'),
    path('resend_otp/',views.sendOTP,name='resend_otp'),
    path('resend_otp_email/',views.sendOTPEmail,name='resend_otp_email'),
    path('interest/',views.save_top_interest_view,name='save_top_interest_view'),

]




 

credentials/models.py
# models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from allauth.account.adapter import DefaultAccountAdapter
from django.contrib.auth import get_user_model

class CustomUser(AbstractUser):
    email = models.EmailField(unique=True) 
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    location = models.CharField(max_length=100, blank=True, null=True)

    # Override fields to remove them from the built-in user model
    last_login = None
    # is_superuser = None
    first_name = None
    last_name = None
    # is_staff = None
    # is_active = None
    date_joined = None


    
    class Meta:
        permissions = [
            ("can_do_something", "Can do something"),
            # Add other permissions as needed
        ]
        


    groups = models.ManyToManyField('auth.Group', related_name='custom_user_set', blank=True, verbose_name='groups')
    user_permissions = models.ManyToManyField('auth.Permission', related_name='custom_user_set', blank=True, verbose_name='user permissions')



class Purpose(models.Model):
    purpose_name = models.CharField(max_length=100)
    def __str__(self):
        return self.purpose_name

# Model to store interest
class Interest(models.Model):
    interest_name = models.CharField(max_length=100)
    def __str__(self):
        return self.interest_name

# Model to store User details which contain the interest and purpose selected by the user
class User_detail(models.Model):
    user=models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    purposes = models.ManyToManyField(Purpose)
    interests = models.ManyToManyField(Interest)




# added **kwargs to accept unexpected values

class CustomAccountAdapter(DefaultAccountAdapter):
    def get_user_model(self):
        return CustomUser

    def clean_username(self, username,**kwargs):
        return username

credentials/forms.py
from .models import CustomUser
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from allauth.account.forms import LoginForm

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('username', 'email','phone_number','date_of_birth','location')

        def clean_email(self):
            email = self.cleaned_data['email']
            # Check if the email already exists in the database
            if CustomUser.objects.filter(email=email).exists():
                raise forms.ValidationError("This email address is already in use.")
            return email

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     # Remove password fields
    #     del self.fields['password1']
    #     del self.fields['password2']

        

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        return cleaned_data



class CustomLoginForm(LoginForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['username'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Username'})
        self.fields['password'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Password'})

credentials/views.py
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.shortcuts import render
from django.contrib.auth import authenticate, login
import random
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm
from allauth.account.views import LoginView,PasswordResetView
from django.core.mail import send_mail
from django.conf import settings
from twilio.rest import Client
from .models import CustomUser
from django.contrib.auth.hashers import make_password
from django.http import HttpResponse, HttpResponseBadRequest
from django.urls import reverse_lazy
from django.core.validators import validate_email, RegexValidator
from django.core.exceptions import ValidationError
from allauth.socialaccount.models import SocialAccount
from allauth.socialaccount.providers.google.views import OAuth2CallbackView
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from allauth.socialaccount.models import SocialAccount
from datetime import datetime
from .models import User_detail
from django.contrib.auth.decorators import login_required
from .models import Purpose, User_detail,Interest

def header(request):
    return render(request,'header.html')

def footer(request):
    return render(request,'footer.html')

phone_regex = r'^\+?1?\d{9,15}$'
name_regex = r'^[a-zA-Z\s]+$'
phone_validator = RegexValidator(
    regex=phone_regex,
    message='Enter a valid phone number.'
)
name_validator = RegexValidator(
    regex=name_regex,
    message='Enter a valid name.'
)

# For the signuprpocess

def signup_view(request):
    errors = {}
    if request.method == 'POST':
        try:
            name_validator(request.POST['name'])
            name = request.POST['name']
        except ValidationError:
            errors['name'] = 'name is invalid'
        try:
            validate_email(request.POST['email'])
            email = request.POST['email']
            if CustomUser.objects.filter(email=email).exists():
                errors['registered email'] = 'email is already registered'
        except ValidationError:
            errors['email'] = 'email is invalid'
        try:
            phone_validator(request.POST['number'])
            number = request.POST['number']
            if CustomUser.objects.filter(phone_number=number).exists():
                errors['registered number'] = 'number is already registered'
        except ValidationError:
            errors['number'] = 'phone number is invalid'
        if not errors:
            request.session['name'] = name
            request.session['email'] = email
            request.session['number'] = number
            #new
            sendOTP(request)
            return render(request, 'accounts/phone_otp.html', {'message': number})
        return render(request, 'accounts/signup.html', {'errors': errors})
    else:
        if request.user.is_authenticated:
            social_accounts = SocialAccount.objects.filter(user=request.user)
            if social_accounts.exists():
                return redirect('accounts/profile')
            else:
                return redirect('socialaccount_signup')
        return render(request, 'accounts/signup.html')
    

# for getting mobile otp
def sendOTP(request):
    otp = ''.join([str(random.randint(0, 9)) for _ in range(6)])
    print(otp)
    request.session['phone_otp'] = otp
    message = f'Your OTP is: {otp}'
    # client = Client(settings.TWILIO_ACCOUNT_SID, settings.TWILIO_AUTH_TOKEN)
    # client.messages.create(
    #     to=request.session['number'],
    #     from_=settings.TWILIO_PHONE_NUMBER,
    #     body=message
    # )
    return render(request, 'accounts/phone_otp.html', {'message': request.session.get('number')})

def phone_otp(request):
    if request.method=='POST':
          otp=request.POST['digit1']+request.POST['digit2']+request.POST['digit3']+request.POST['digit4']+request.POST['digit5']+request.POST['digit6']
          if request.session.get('phone_otp')==otp:
            return redirect('signup_password')
    return render(request,'accounts/phone_otp.html')

# for giving passwords

def signup_password(request):
    if request.method=='POST':
        password=request.POST.get('password')
        confirm_password=request.POST.get('confirm_password')
        if password==confirm_password:
            request.session['password']=request.POST['password']
            return redirect('dob')
        return render(request, 'accounts/signup_password.html', {'message':"passwords don't match. try again"})
    return render(request,'accounts/signup_password.html')


# for giving date of birth of user

def signup_dob(request):
    if request.method == 'POST':
        day = request.POST.get('day')
        month = request.POST.get('month')
        year = request.POST.get('year')
        try:
            date_of_birth = datetime.strptime(f"{year}-{month}-{day}", '%Y-%m-%d').date()
        except ValueError:
            pass
        modified_post = request.POST.copy()
        modified_post['date_of_birth'] = date_of_birth
        modified_post['username'] = request.session.get('name')
        modified_post['email'] = request.session.get('email')
        modified_post['password1'] = request.session.get('password')
        modified_post['password2'] = request.session.get('password')
        modified_post['phone_number'] = request.session.get('number')
        form = CustomUserCreationForm(modified_post)
        if form.is_valid():
            form.save()
            #new
            user = authenticate(request, email=request.session.get('email'), password=request.session.get('password'))
            if user is not None:
                login(request, user)
            return redirect('save_top_purposes_view')
    else:
        form = CustomUserCreationForm()
    return render(request, 'accounts/dob.html',{'form':form})

# For saving the purposes selected by the user

@login_required
def save_top_purposes_view(request):
    if request.method == 'POST':
        selected_purpose_ids = request.POST.get('selected_purposes').split(',')[:5]  # Limit to top 5 purposes
        if selected_purpose_ids:
            user = request.user
            if user:
                user_detail, created = User_detail.objects.get_or_create(user=user)
                user_detail.purposes.clear()
                for purpose_id in selected_purpose_ids:
                    purpose = Purpose.objects.get(id=int(purpose_id))
                    user_detail.purposes.add(purpose)
                    print(user_detail.purposes)
                return redirect('save_top_interest_view')
    purposes = Purpose.objects.all()
    return render(request, 'accounts/purposes.html', {'purposes': purposes})

# For saving the interests selected by the user

@login_required
def save_top_interest_view(request):
    if request.method == 'POST':
        selected_interests_data = request.POST.get('selected_interests')
        if selected_interests_data:
            selected_interest_ids = selected_interests_data.split(',')[:3]
            user = request.user
            if user:
                user_detail, created = User_detail.objects.get_or_create(user=user)
                user_detail.interests.clear()
                for interest_id in selected_interest_ids:
                    try:
                        interest = Interest.objects.get(id=int(interest_id))
                        user_detail.interests.add(interest)
                    except Interest.DoesNotExist:
                        pass  
                return redirect('my_view')
    interests = Interest.objects.all()
    return render(request, 'accounts/interest.html', {'interests': interests})


def profile(request):
    return render(request,'accounts/profile.html')


#Modified code for login using normal way and social authenticaation
class CustomLoginView(LoginView):
    template_name = 'accounts/login.html'
    success_url = reverse_lazy('profile')  # Default success URL

    def post(self, request, *args, **kwargs):
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            return render(request, 'accounts/profile.html', {'username': user.username})
        else:
            return super().post(request, *args, **kwargs)  
        
def google_oauth_callback(request):
    user_data = request.user.socialaccount.extra_data
    print("User Data from Google OAuth:", user_data)
    keys = user_data.keys()
    print("Keys in User Data:", keys)
    return redirect('profile')


# Password reseting 
class CustomPasswordResetView(PasswordResetView):
    template_name='accounts/login_forgot password.html'
    def form_valid(self, form):
        email=form.cleaned_data['email']
        #new
        self.request.session['email']=email
        if CustomUser.objects.filter(email=email).exists():
            #new
            sendOTPEmail(self.request)
            return render(self.request, 'accounts/otp_verification.html')
        else:
            message={'message':'email address does not exist. Try another one'}
            return render(self.request, 'accounts/otp_verification.html',{'message':message['message']})


# Sending otp through mail 

def sendOTPEmail(request):
    otp = ''.join([str(random.randint(0, 9)) for _ in range(6)])
    email=request.session['email']
    send_mail(
        'Password Reset OTP',
        f'Your OTP is: {otp}',
        settings.DEFAULT_FROM_EMAIL,
        [email],
        fail_silently=False,
    )
    request.session['reset_otp'] = otp
    return render(request, 'accounts/otp_verification.html')


# Verifying otp
def verify_otp(request):
    if request.method == 'POST':
        entered_otp=request.POST['digit1']+request.POST['digit2']+request.POST['digit3']+request.POST['digit4']+request.POST['digit5']+request.POST['digit6']

credentials/templates/accounts/custom_password_reset.html
{% comment %} <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reset Password</title>
</head>
<body>
    <h1>Reset Password</h1>
    <form method="post" action="{% url 'reset_password' %}">
        {% csrf_token %}
        <label>New Password:</label>
        <input type="text" name="password"/>
        <label>Re-enter Password</label>
        <input type="text" name="confirm_password" />
        <button type="submit">submit</button>
    </form>
    <div>{{message}}</div>
</body>

</html> {% endcomment %}
{% load static %}
{% include 'header.html' %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% block styles %}
<style>
    .left-column {
        border-right: none;
        width:400px
    }
    .login-optionsa{
        display: flex;
         margin-left:110px; 
        margin-top:50px;
    }
    .b-test{
        margin-left:110px;
        margin-top:40px;
    }
    .left-column form input {
        margin-bottom: 10px;
        padding: 5px;
        width: 100%;
        height:50px;
    }
    .continue-button{
        width:100%;
    }
</style>
{% endblock %}
{% block body %}
<div class="wrapper">
    <div class="content"> 
        <div class="square">
            <div class="b-test"><svg width="58" height="58" viewBox="0 0 58 58" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M28.6514 39.0326C33.2799 39.0326 36.8693 35.403 36.8693 30.4161C36.8693 25.4293 33.3113 21.8312 28.6829 21.8312C26.1325 21.8312 23.9914 22.9043 22.8264 24.8296H22.543V15.2031H19.9297V38.4014H22.543V35.9395H22.8264C23.9914 37.8964 26.038 39.0326 28.6514 39.0326ZM28.368 36.6655C24.936 36.6655 22.4486 33.9196 22.4486 30.4161C22.4486 26.9127 24.936 24.1984 28.368 24.1984C31.7685 24.1984 34.2559 26.9127 34.2559 30.4161C34.2559 33.9827 31.7685 36.6655 28.368 36.6655Z" fill="black"/>
                <path d="M39.5623 38.8117C40.5699 38.8117 41.2941 38.0858 41.2941 37.0758C41.2941 36.0658 40.5699 35.3399 39.5623 35.3399C38.5233 35.3399 37.8306 36.0658 37.8306 37.0758C37.8306 38.0858 38.5233 38.8117 39.5623 38.8117Z" fill="black"/>
                </svg>
            </div>
            <div class="login-optionsa">
                <div class="left-column">  
                    <div class="left-svg">
                        <div class="left-title">
                            RESET PASSWORD
                        </div>
                    </div>  
                    <form method="post" action="{% url 'reset_password' %}">
                        {% csrf_token %}
                        <input type="text" placeholder="Set New Password" name="password"/>
                        <br/>
                        <input type="text" placeholder="Confirm New Password" name="confirm_password"/>
                        <br/>
                        <button type="submit" class="continue-button">RESET PASSWORD</button> 
                    </form>
                    <div>{{message}}</div>
                </div> 
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% include 'footer.html' %}

credentials/templates/accounts/dob.html
{% comment %} <form method="post" action="{% url 'dob' %}">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_date_of_birth">Date of Birth:</label>
        <input type="date" name="date_of_birth" id="id_date_of_birth" class="form-control" placeholder="Date of Birth">
    </div>
    
    <div class="form-group">
        <label for="id_location">Location:</label>
        <input type="text" name="location" id="id_location" class="form-control" placeholder="Location">
    </div>
    <button type="submit" class="btn btn-primary">Sign Up</button>
</form> {% endcomment %}
{% load static %}
{% include 'header.html' %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% block styles %}
<style>
    .content-container{
        height: auto;
        display: flex;
        width: 445px;
    }
.step{
    font-family: Inter;
    font-size: 13px;
    font-weight: 500;
    color: #666666;
    margin-top:50px;
    margin-left:60px;
    }
.b-test{
  margin-left:60px; 
    margin-top:40px;
}
.birthday {
    font-size: 20px;
    font-weight: bold;
    margin-left:60px;
    margin-top:10px;
    
}
/* CSS for form layout */
.form-row {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    width:fit-content;
    margin-top:25px;
}



.form-group.col {
    margin-top:50px;
    justify-content:center;
}
.form-birthday{
    margin-left:30px;

}
.form-group {
    margin-bottom: 1rem;
    margin-right: 1rem; /* Adjust the margin between input boxes */
}
.form-control{
      width:100%;
      height:40px;
      padding-left: 5px;
      color: #969696;
}
.para-dob{
    margin-top:10px;
    margin-right:10px;
    font-size:14px;
    color: #969696;

}
.location
{
    margin-right:60px;
    font-size: 20px;
    font-weight: bold;
    margin-top:10px;
}
.form-location{
    width:488px;
    margin-top:20px;
}
.para2{
    margin-top:20px;
    font-size:14px;
    color: #969696;

}
.square{
    height:555px;
    padding-right:100px;
   
}
.continue-button{
    width:485px;
}
.form-row div{
    margin-right: 20px;
}
.col-day{
    width:95px;

}
.col-my{
    width:175px;
}
.content{
    margin-top:57px;
    margin-bottom:57px;
}

</style>
{% endblock %}
{% block body %}
<div class="wrapper">
    <div class="content"> 
        <div class="square">
            <div class="b-test"><svg width="23" height="25" viewBox="0 0 23 25" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M9.65138 24.0326C14.2799 24.0326 17.8693 20.403 17.8693 15.4161C17.8693 10.4293 14.3113 6.8312 9.68286 6.8312C7.13248 6.8312 4.99141 7.90432 3.82642 9.82962H3.54305V0.203125H0.929688V23.4014H3.54305V20.9395H3.82642C4.99141 22.8964 7.03802 24.0326 9.65138 24.0326ZM9.368 21.6655C5.936 21.6655 3.44859 18.9196 3.44859 15.4161C3.44859 11.9127 5.936 9.19838 9.368 9.19838C12.7685 9.19838 15.2559 11.9127 15.2559 15.4161C15.2559 18.9827 12.7685 21.6655 9.368 21.6655Z" fill="black"/>
                <path d="M20.5623 23.8117C21.5699 23.8117 22.2941 23.0858 22.2941 22.0758C22.2941 21.0658 21.5699 20.3399 20.5623 20.3399C19.5233 20.3399 18.8306 21.0658 18.8306 22.0758C18.8306 23.0858 19.5233 23.8117 20.5623 23.8117Z" fill="black"/></svg>
            </div> 
            <div class="content-container">
                <div class="content-box">
                <div class="step">Step 4/6</div>
                <div class="birthday">
                    When is your Birthday?
                </div>
                <div class="form-birthday">
                    <div class="form-birthday">
                        <form method="post" action="{% url 'dob' %}">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="col-day">
                                    <input type="number" name="day" id="id_day" class="form-control" placeholder="Day" min="1" max="31">
                                </div>
                                <div class="col-my">
                                    <select name="month" id="id_month" class="form-control">
                                        <option value="" disabled selected hidden class="month">Month</option>
                                        <option value="1">January</option>
                                        <option value="2">February</option>
                                        <option value="3">March</option>
                                        <option value="4">April</option>
                                        <option value="5">May</option>
                                        <option value="6">June</option>
                                        <option value="7">July</option>
                                        <option value="8">August</option>
                                        <option value="9">September</option>
                                        <option value="10">October</option>
                                        <option value="11">November</option>
                                        <option value="12">December</option>
                                    </select>
                                </div>
                                <div class="col-my">
                                    <input type="number" name="year" id="id_year" class="form-control" placeholder="Year" min="1900" max="2099">
                                </div>
                            </div>
                            <div class="para-dob">
                                Knowing your birth date allows us to enhance your blooming experience
                            </div>  
                            <div class="location">
                                Where are you currently based of ?
                            </div> 
                        <div class="form-location">
                        <input type="text" name="location" id="id_location" class="form-control" placeholder="Location">
                        </div>
                         <div class="para2">
                            Knowing your location allows us to connect you locally with the community
                        </div>
                        <div>
                            <button type="submit" class="continue-button">Next</button> 
                        </div>
                        </form>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% include 'footer.html' %}

credentials/templates/accounts/interest.html
{% load static %}
{% include "header.html" %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{%block styles %}
<style>
.square{
    height:515px;
    padding-right:100px;
    width:600px;
}
.content-container{
    height: auto;
    display: flex;
    width: 445px;
    }
.step{
    font-family: Inter;
    font-size: 13px;
    font-weight: 500;
    color: #666666;
    margin-bottom:5px;
    margin-right:30px;
    }
.selected {
    background-color: black;
    color: white; 
    }

.right{
    background: #8FC7FF;
    width:300px;
    margin-left:125px;
    position: relative;
}
.content{
    display: flex;
    justify-content: right;
    height:570px;
    margin-left: 100px;
    margin-top:58px;
}

.wrapper2{
    display:flex;
    justify-content: flex-end;
}

.left{
    height: 300px;
}
.saly{
    height:fit-content;
    width: fit-content;
}

.saly img{
    width:343px;
    height:570px;
    z-index:1;
    position:absolute;
    right:70px;
    top:59px;
}

.want{
    font-size: 24px;
    font-weight: bold;
    font-family:'Inter', sans-serif;
    margin-top:31px;
}

.para4{
    font-size:13px;
    font-family:'Inter', sans-serif;
    color: #666666;
    margin-top:20px;
    margin-bottom:15px;

}
.buttons
{
    margin-top:20px;
    width:260px;
    height:30px;
    display:flex;
    justify-content:space-between;
}
.button1{
    width:117px;
    background: #3E46E0;
    color:white;
    border:0px;

  
}
.button1:hover{
    cursor:pointer;
    transform:scale(1.1)
}

.interest-button {
    background-color: white;
    color: black;
    border: 1px solid black;
    padding: 2px 10px;
    margin: 4px;
    cursor: pointer;
    transition: background-color 0.3s ease;
    height:24px;
  }
  
  .interest-button.selected {
    background-color: black;
    color: white;
  }

</style>
{% endblock%}


{% block body %}
<div class="wrapper2">
    <div class="content"> 
        <div class="left">
            <div class="square">
                <div class="b">
                    <svg width="58" height="58" viewBox="0 0 58 58" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M28.6514 39.0326C33.2799 39.0326 36.8693 35.403 36.8693 30.4161C36.8693 25.4293 33.3113 21.8312 28.6829 21.8312C26.1325 21.8312 23.9914 22.9043 22.8264 24.8296H22.543V15.2031H19.9297V38.4014H22.543V35.9395H22.8264C23.9914 37.8964 26.038 39.0326 28.6514 39.0326ZM28.368 36.6655C24.936 36.6655 22.4486 33.9196 22.4486 30.4161C22.4486 26.9127 24.936 24.1984 28.368 24.1984C31.7685 24.1984 34.2559 26.9127 34.2559 30.4161C34.2559 33.9827 31.7685 36.6655 28.368 36.6655Z" fill="black"/>
                        <path d="M39.5623 38.8117C40.5699 38.8117 41.2941 38.0858 41.2941 37.0758C41.2941 36.0658 40.5699 35.3399 39.5623 35.3399C38.5233 35.3399 37.8306 36.0658 37.8306 37.0758C37.8306 38.0858 38.5233 38.8117 39.5623 38.8117Z" fill="black"/>
                    </svg>
                </div> 
                <div class="content-container">
                    <div class="content-box">
                        <div class="step">Step 6/6</div>
                        <div class="want">What are your Top 3 Interests? </div>
                        <div class="para4">Search for your favourite interests, anything from art to artificial intelligence.</div>
                        <form method="POST" action="{% url 'save_top_interest_view' %}">
                            {% csrf_token %}
                            <div>
                                {% for interest in interests %}
                                    <button type="button" class="interest-button" data-interest-id="{{ interest.id }}">{{ interest.interest_name }}</button>
                                {% endfor %}
                            </div>
                            <div class="buttons">
                                <input type="hidden" name="selected_interests" id="selected_interests" value="">
                                <button type="submit" class="button1">Finish</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="right">
        <div class="saly">
        <img src="{% static 'img/Saly-14.png' %}">
        </div>
    </div>
</div>

<script>
var selectedInterests = [];

// Attach click event listeners to the purpose buttons
document.querySelectorAll('.interest-button').forEach(function(button) {
    button.addEventListener('click', function() {
        var interestId = this.getAttribute('data-interest-id');
        toggleInterest(interestId);
    });
});

function toggleInterest(interestId) {
    var index = selectedInterests.indexOf(interestId);
    if (index === -1) {
        selectedInterests.push(interestId);
        document.querySelector('.interest-button[data-interest-id="' + interestId + '"]').classList.add('selected');
    } else {
        selectedInterests.splice(index, 1);
        document.querySelector('.interest-button[data-interest-id="' + interestId + '"]').classList.remove('selected');
    }
    document.getElementById('selected_interests').value = selectedInterests.join(',');
}
</script>

{% endblock %}
{% include "footer.html" %}